### ISSUE TITLE
Error 207 Multistatus - Apache2 proxy

### ISSUE THREAD

**Issue by lil5** [micromata/dave#11]
The given Apache example does not work for me.
```
<VirtualHost *:443>
  ServerName localhost

  SSLEngine On
  SSLProxyEngine On
  SSLProxyCheckPeerCN Off
  SSLCertificateFile    /data/cert.pem
  SSLCertificateKeyFile /data/key.pem

  ProxyRequests Off
  ProxyPreserveHost On

  RewriteEngine On
  RewriteRule ^/webdav$ /webdav/ [R,L]
  RewriteRule ^/radicale$ /radicale/ [R,L]

  <Location /webdav/>
  ProxyPass           http://localhost:8081/
  ProxyPassReverse    http://localhost:8081/
  </Location>

  <Location "/radicale/">
    ProxyPass        http://localhost:5232/ retry=0
    ProxyPassReverse http://localhost:5232/
    RequestHeader    set X-Script-Name /radicale/
  </Location>

</VirtualHost>
```

```
address: "127.0.0.1"    # the bind address
port: "8081"            # the listening port
dir: "/data/webdav/data"     # the provided base dir
#prefix: "/webdav"       # the url-prefix of the original url
users:
  user:
    password:
```
